
CREATE TABLE address (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nationality VARCHAR(150),
    state       VARCHAR(100),
    city        VARCHAR(100),
    line_2      VARCHAR(255),
    line_1      VARCHAR(50),
    zip_code    VARCHAR(100),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE users_roles (
    user_id VARCHAR,
    role varchar (100),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE users_avatar (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type    VARCHAR(255),
    name    VARCHAR(255),
    avatar  OID,
    user_id VARCHAR(255),
    CONSTRAINT pk_users_avatar PRIMARY KEY (id)
);

ALTER TABLE users_avatar
    ADD CONSTRAINT FK_USERS_AVATAR_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD COLUMN email_verified BOOLEAN NOT NULL default false,
    ADD COLUMN email_verification_key VARCHAR(10),
    ADD COLUMN date_of_birth VARCHAR(30),
    ADD COLUMN gender VARCHAR(30),
    ADD COLUMN address_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);
